name: mensuel-precalc

on:
  schedule:
    - cron: "0 6 1 * *"  # 06:00 UTC le 1er du mois
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer dépendances
        run: pip install jupytext papermill nbformat pandas ipykernel

      - name: Convertir le .py en .ipynb (Jupytext)
        run: |
          jupytext --to ipynb notebooks/Backtest_V10_4Univers.py \
                   -o notebooks/Backtest_V10_4Univers.ipynb

      - name: Créer le dossier de sortie
        run: mkdir -p out

      - name: Exécuter le notebook (Papermill)
        run: |
          papermill notebooks/Backtest_V10_4Univers.ipynb out/out.ipynb \
            -p EXECUTION_DAY first_business_day \
            -p DEPUIS "2014-01" \
            -p JUSQUA "2025-12"

      - name: Définir le tag du mois (UTC)
        id: tag
        run: echo "tag=$(date -u +'%Y-%m')" >> $GITHUB_OUTPUT

      - name: Lister les fichiers produits (debug)
        run: |
          echo "::group::Arborescence"
          ls -R
          echo "::endgroup::"
          echo "::group::Contenu de out/"
          ls -l out || true
          echo "::endgroup::"

      - name: Publier les résultats
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ steps.tag.outputs.tag }}
          path: |
            out/*.ipynb
            out/*.csv
          retention-days: 10
