name: Mensuel-precalc

on:
  schedule:
    - cron: "0 6 1 * *"  # 06:00 UTC le 1er du mois
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier si dernier jour du mois
        id: gate
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "run=true" >> $GITHUB_OUTPUT
          elif [ "$(date -u -d 'tomorrow' +%d)" = "01" ]; then
            echo "run=true" >> $GITHUB_OUTPUT
          else
            echo "run=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v4
        if: steps.gate.outputs.run == 'true'

      - uses: actions/setup-python@v5
        if: steps.gate.outputs.run == 'true'
        with:
          python-version: "3.11"

      - name: Installer dépendances
        if: steps.gate.outputs.run == 'true'
        run: pip install jupytext papermill jupyter nbformat pandas

      - name: Convertir le .py en .ipynb
        if: steps.gate.outputs.run == 'true'
        run: |
          jupytext --to ipynb notebooks/Backtest_V10_4Univers.py \
                   -o notebooks/Backtest_V10_4Univers.ipynb

      - name: Exécuter le notebook (Papermill)
        if: steps.gate.outputs.run == 'true'
        run: |
          papermill notebooks/Backtest_V10_4Univers.ipynb out/out.ipynb \
            -p EXECUTION_DAY first_business_day \
            -p DEPUIS "2014-01" -p JUSQUA "2025-12"

      - name: Publier le CSV d’ordres
        if: steps.gate.outputs.run == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: orders
          path: out/*.csv
